version: "3"

networks:
  frontend:
    external: true
  app:
    driver: bridge
    internal: false

services:
  node:
    image: node:10
    networks:
      - app
      - frontend
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    depends_on:
      - mariadb
    volumes:
      - ./:/home/node/app
    ports:
      - "3000"
    command: "npm run start-dev"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_DOMAIN}`)"

  mariadb:
    image: itkdev/mariadb:latest
    networks:
      - app
    ports:
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=db
      - MYSQL_PASSWORD=db
      - MYSQL_DATABASE=db

  influxdb:
    image: influxdb:1.8
    networks:
      - app
    ports:
      - '8086'
    environment:
      - INFLUXDB_DB=sensor

  telegraf:
    image: telegraf:1.14
    networks:
      - app
    ports:
      - '8186'
    depends_on:
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf

  kapacitor:
    image: kapacitor:1.5
    networks:
      - app
    ports:
      - '9092'
    depends_on:
      - influxdb
    environment:
      - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086

  chronograf:
    image: chronograf:1.8
    depends_on:
      - influxdb
    networks:
      - app
    ports:
      - '8888'
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_DB=sensor
      - KAPACITOR_URL=http://kapacitor:9092
