version: "3"

networks:
  frontend:
    external: true
  app:
    driver: bridge
    internal: false

services:
  node:
    image: node:10
    networks:
      - app
      - frontend
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    depends_on:
      - mariadb
    volumes:
      - ./:/home/node/app
    ports:
      - "3000"
    command: "npm run start"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_DOMAIN}`)"

  mariadb:
    image: itkdev/mariadb:latest
    networks:
      - app
    ports:
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=db
      - MYSQL_PASSWORD=db
      - MYSQL_DATABASE=db
